// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3A18L2Xmd1AGG2-7eYtnNOV8o5nSDEP0',
    appId: '1:316938228019:android:d3f10be2baab763bedee46',
    messagingSenderId: '316938228019',
    projectId: 'hs-fashion-store',
    storageBucket: 'hs-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwFrwJ4FXkTqQODaSDXe4BMo6qsb-zC1Q',
    appId: '1:316938228019:web:50e4959d280c9007edee46',
    messagingSenderId: '316938228019',
    projectId: 'hs-fashion-store',
    authDomain: 'hs-fashion-store.firebaseapp.com',
    storageBucket: 'hs-fashion-store.firebasestorage.app',
    measurementId: 'G-TVXDGK1DVT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3PsKbXaE9Gl0EkW4yUg13Pvr1YKCsICo',
    appId: '1:316938228019:ios:8fa0780843947b52edee46',
    messagingSenderId: '316938228019',
    projectId: 'hs-fashion-store',
    storageBucket: 'hs-fashion-store.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3PsKbXaE9Gl0EkW4yUg13Pvr1YKCsICo',
    appId: '1:316938228019:ios:8fa0780843947b52edee46',
    messagingSenderId: '316938228019',
    projectId: 'hs-fashion-store',
    storageBucket: 'hs-fashion-store.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwFrwJ4FXkTqQODaSDXe4BMo6qsb-zC1Q',
    appId: '1:316938228019:web:641d027790beaa44edee46',
    messagingSenderId: '316938228019',
    projectId: 'hs-fashion-store',
    authDomain: 'hs-fashion-store.firebaseapp.com',
    storageBucket: 'hs-fashion-store.firebasestorage.app',
    measurementId: 'G-3CBTW1LJ08',
  );
}
